import {
  LIBRARY_LAYERS,
  type LIBRARY_KINDS,
  type LibraryAdditionEventView,
  type LibraryArtifactView,
  type LibraryEntry,
  type LibraryLayerName,
  type VariantFamilyView,
} from "./api-contract";

/**
 * Pure view model of the library drawer (design plan §17.1, roadmap N32): filtering, grouping and
 * the text labels that keep provenance and approval distinctions visible without colour. Nothing
 * here recomputes admission or variants; it only describes what the worker returned.
 */

export type LibraryFilter = Readonly<{
  query: string;
  kind: "all" | (typeof LIBRARY_KINDS)[number];
  domain: "all" | string;
  layer: "all" | LibraryLayerName;
}>;

export const EMPTY_FILTER: LibraryFilter = { query: "", kind: "all", domain: "all", layer: "all" };

export const LAYER_LABELS: Readonly<Record<LibraryLayerName, string>> = {
  global: "Global (approved catalog and packs)",
  "initial-problem": "Initial problem",
  "proof-time-background": "Proof-time background",
  derived: "Derived in this session",
  "move-discovery-draft": "Move-discovery draft",
};

export const KIND_LABELS: Readonly<Record<(typeof LIBRARY_KINDS)[number], string>> = {
  definition: "Definition",
  result: "Result",
  technique: "Technique",
  move: "Move",
};

export function layerLabel(layer: LibraryLayerName): string {
  return LAYER_LABELS[layer];
}

export function kindLabel(kind: LibraryArtifactView["kind"]): string {
  return KIND_LABELS[kind];
}

/** The approval status as text; a draft is never presented as approved. */
export function approvalLabel(approval: LibraryArtifactView["approval"]): string {
  switch (approval.status) {
    case "approved":
      return `Approved (reviewer ${approval.reviewerId})`;
    case "draft":
      return "Draft (not approved)";
    case "rejected":
      return `Rejected: ${approval.reason}`;
  }
}

export function approvalStatusLabel(approval: LibraryArtifactView["approval"]): string {
  return approval.status === "approved"
    ? "Approved"
    : approval.status === "draft"
      ? "Draft"
      : "Rejected";
}

/** How the artifact came to exist, in words. */
export function provenanceLabel(provenance: LibraryArtifactView["provenance"]): string {
  switch (provenance.kind) {
    case "curated":
      return `Curated: ${provenance.source}`;
    case "imported":
      return `Imported: ${provenance.source}`;
    case "generated":
      return `Generated by ${provenance.role} (context ${provenance.contextId})`;
    case "derived":
      return `Derived in session ${provenance.sessionId} at node ${provenance.proofNodeId}`;
    case "derived-variant":
      return `Variant of ${provenance.sourceId} (${provenance.transformation})`;
  }
}

export function sourceLabel(source: LibraryEntry["source"]): string {
  return source === "approved-catalog" ? "Approved catalog" : "Stored library";
}

export const entryKey = (entry: LibraryEntry): string => `${entry.source}:${entry.artifact.id}`;

function searchText(entry: LibraryEntry): string {
  const { artifact } = entry;
  return [
    artifact.id,
    artifact.name,
    artifact.description,
    artifact.renderings.latex,
    artifact.renderings.naturalLanguage,
    artifact.classification.level,
    ...artifact.classification.domains,
    provenanceLabel(artifact.provenance),
  ]
    .join("\n")
    .toLowerCase();
}

/** Entries matching every set criterion; the query matches all of its words, in any order. */
export function filterEntries(
  entries: readonly LibraryEntry[],
  filter: LibraryFilter,
): readonly LibraryEntry[] {
  const words = filter.query.toLowerCase().split(/\s+/).filter(Boolean);
  return entries.filter((entry) => {
    const { artifact } = entry;
    if (filter.kind !== "all" && artifact.kind !== filter.kind) return false;
    if (filter.layer !== "all" && artifact.layer !== filter.layer) return false;
    if (filter.domain !== "all" && !artifact.classification.domains.includes(filter.domain)) {
      return false;
    }
    if (words.length === 0) return true;
    const text = searchText(entry);
    return words.every((word) => text.includes(word));
  });
}

/** The domains present in the library, sorted. */
export function availableDomains(entries: readonly LibraryEntry[]): readonly string[] {
  return [...new Set(entries.flatMap(({ artifact }) => artifact.classification.domains))].sort();
}

export type LayerGroup = Readonly<{ layer: LibraryLayerName; entries: readonly LibraryEntry[] }>;

/** Non-empty layer groups in the canonical layer order; entries keep the worker's order. */
export function groupByLayer(entries: readonly LibraryEntry[]): readonly LayerGroup[] {
  return LIBRARY_LAYERS.map((layer) => ({
    layer,
    entries: entries.filter(({ artifact }) => artifact.layer === layer),
  })).filter(({ entries: inLayer }) => inLayer.length > 0);
}

/** Count of entries per layer, including empty layers, for the layer summary. */
export function layerCounts(
  entries: readonly LibraryEntry[],
): readonly Readonly<{ layer: LibraryLayerName; count: number }>[] {
  return LIBRARY_LAYERS.map((layer) => ({
    layer,
    count: entries.filter(({ artifact }) => artifact.layer === layer).length,
  }));
}

export type VariantFamilyDetail = Readonly<{
  family: VariantFamilyView;
  members: readonly Readonly<{ id: string; entry: LibraryEntry | undefined }>[];
}>;

/** The variant family a result belongs to, with its members that are in the library. */
export function variantFamilyDetail(
  artifact: LibraryArtifactView,
  families: readonly VariantFamilyView[],
  entries: readonly LibraryEntry[],
): VariantFamilyDetail | undefined {
  const family = families.find(({ id }) => id === artifact.variantFamilyId);
  if (family === undefined) return undefined;
  return {
    family,
    members: family.memberIds.map((id) => ({
      id,
      entry: entries.find((entry) => entry.artifact.id === id),
    })),
  };
}

/** A rejected event is an event whose admission gate refused the artifact. */
export function admissionLabel(event: LibraryAdditionEventView): string {
  return event.admission.decision === "admitted" ? "Admitted" : "Rejected";
}

export function originLabel(origin: LibraryAdditionEventView["origin"]): string {
  return origin.actorId === undefined ? origin.kind : `${origin.kind} (${origin.actorId})`;
}
