packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

engineStrict: true
enableGlobalVirtualStore: false
saveExact: false
sharedWorkspaceLockfile: true
strictPeerDependencies: true
verifyDepsBeforeRun: error
